#
# Tests for the MRG32k3a generator
#
# These numbers were generated by the `stream` utility, which can be
# compiled by running `scons` in the `lecuyer` directory.
#
#

seeds = Array[[12345, 12345, 12345, 12345, 12345, 12345]]

sums = [5001090.947189088]

firsts = Array[[
                0.12701112204657714,
                0.3185275653967945,
                0.30918601558327008,
                0.82584686292711362,
                0.2216299157820229,
                0.53339538791827878,
                0.4807742033156181,
                0.35555987943812623,
                0.13598841039594017,
                0.75585223716154359
                ]]

lasts = Array[[
               0.2498925616912667,
               0.49652759527734946,
               0.16011136148664246,
               0.86792338721641915,
               0.55630523262347298,
               0.57194505957061714,
               0.067721477496919064,
               0.63141833393252778,
               0.17481334748705299,
               0.90130638318875056
               ]]

#
# Primary tests -- these test that the actual implementation conforms
# to the standard implementation. Now with state Cg test
#                
for i = 1:length(seeds)
    gen = MRG32k3a(seeds[i])

    first = Array(Float64, 0)
    last = Array(Float64, 0)

    _sum = 0
    for j = 1:10^7
        z = rand(gen)
        _sum += z

        if j <= 10
            append!(first, [z])
        elseif j > 10^7 - 10
            append!(last, [z])
        end
    end

    @test _sum == sums[i]
    @test all(first .== firsts[i]);
    @test all(last .== lasts[i]);
end
   
#
# Test that the various overloads of `rand` return the proper type.
#

rng = MRG32k3a([12345, 12345, 12345, 12345, 12345, 12345])
@test typeof(rand(rng)) == Float64
@test typeof(rand(rng, Float64)) == Float64
@test typeof(rand(rng, Float32)) == Float32
@test typeof(rand(rng, Float16)) == Float16

#
# Test AdvanceState against original implementation
#

rng = MRG32k3a([1,2,3,4,5,6])
AdvanceState(rng, 23, 1611392) 
@test rng.Cg == [2437590332, 1899628456, 3114422128, 2899718867, 1085495888, 737655219] 
